package com.taotaotech.dao;

import com.taotaotech.core.persistence.CrudMapper;
import com.taotaotech.domain.Purchasement;
import org.springframework.stereotype.Repository;

@Repository
public interface PurchasementMapper extends CrudMapper<Purchasement> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchasement
     *
     * @mbggenerated Fri Oct 02 12:08:59 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchasement
     *
     * @mbggenerated Fri Oct 02 12:08:59 CST 2015
     */
    int insert(Purchasement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchasement
     *
     * @mbggenerated Fri Oct 02 12:08:59 CST 2015
     */
    int insertSelective(Purchasement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchasement
     *
     * @mbggenerated Fri Oct 02 12:08:59 CST 2015
     */
    Purchasement selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchasement
     *
     * @mbggenerated Fri Oct 02 12:08:59 CST 2015
     */
    int updateByPrimaryKeySelective(Purchasement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchasement
     *
     * @mbggenerated Fri Oct 02 12:08:59 CST 2015
     */
    int updateByPrimaryKey(Purchasement record);
}